export const SET_SEARCH_TITLE = 'SET_SEARCH_TITLE';
export const SET_USER_FILTER = 'SET_USER_FILTER';
export const SET_ITEMS = 'SET_ITEMS';
export const PUSH_TO_ITEMS = 'PUSH_TO_ITEMS';
export const SET_LOADING = 'SET_LOADING';
export const SET_PAGINATOR = 'SET_PAGINATOR';
export const SET_CLICKED_LOADING = 'SET_CLICKED_LOADING';
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';